name: Test Pipeline

on:
  push:
    branches: [dev]
    paths-ignore:
      - '**.md'
      - '.github/filters.yml'
  pull_request:
    branches: [main, stage]
    paths-ignore:
      - '**.md'
      - '.github/filters.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  typo-check:
    uses: ./.github/workflows/_typo-check.yml

  tests-services:
    uses: ./.github/workflows/_run-tests.yml

